### ISSUE TITLE
Just started having a problem in Thunderbird 91

### ISSUE THREAD

**Issue by BillH99999** [wshanks/tbkeys#81]
I have been using the add-on for a while now and never had any problems until updating to Thunderbird 91.  I never had this problem in TB 78.

Here are the steps to reproduce the problem.

1.  Go to the add on manager in TB
2.  Go to the search box at the top right of the page
3. Type in something in the search box
4. Hit Enter which opens a "browser" tab in Thunderbird displaying the Add-ons page
5. Go to the search box in the top right of this Add-ons page in the "browser" tab
6. Try to type something in the search box... not all characters will type into the box.  For example, "a" and "s" do not type in
the field, but "d" and "g" do.

If I go to the same page in Firefox or Chrome, the search field works fine.  I don't have this problem in any other part of Thunderbird or in any other program either.

With the add-on disabled, I have no problems typing into that search box.

Let me know if I can provide any additional information.

Thanks,
Bill

**Comment by wshanks** [comment]
I have not had a chance to test this but it sounds reasonable. The add-on checks the selected element to determine if it should capture shortcut keys or let them through and all the textbox-like elements are hard-coded. There must have been some new one used that the code does not have listed at the moment. The way I usually check for this is to edit the code and have it log the properties of the selected element on key events to figure out what needs to be added to the textbox check.

**Comment by BillH99999** [comment]
Thanks.  I hope you will be able to find a fix.  In case it makes any difference, the problem occurs for me even if I use just the default key settings.  I uninstalled and re-installed the add-on and still get the problem.

Bill

**Comment by m707** [comment]
Same is true for an editor session the sieve plugin:

https://github.com/thsmi/sieve/

is opening. Since TB91 I have to c&p my changes to sieve scripts to avoid the actions from tbkeys. Everything was fine in TB78.

**Comment by wshanks** [comment]
I looked at this some now. In the debugger I see that when the built-in browser tab for the addons page has focus the element's tagName is "browser". I can add that to the set of tags that tbkeys ignores. I poked around at the browser object but couldn't see how to access its internal state. So I don't see how to detect if a text element has focus inside of the browser. For now, I will just ignore the entire browser tab. If someone finds a way to ignore just selected text elements in the browser, we could do that.

I tried installing sieve, but I could not get to the editor UI because I do not have account with an email provider that supports sieve. @m707 if you want, you can try to figure out yourself what element needs to be ignored. Here are the steps I used:

1. Open the developer toolbox (ctrl+shift+i, or tools->developer tools->developer toolbox).
2. ctrl+shift+f and search for "tbkeys"
3. Click on a line from "implementation.js" to open the file (for me this is the only file in wihch "tbkeys" is found by the search).
4. Click on a line number inside of `stopCallback` to set a breakpoint there (like the `let firstCombo = combo;` line).
5. Press a key in the sieve editor to trigger the breakpoint.
6. In the right hand pane of the toolbox window, there will be a "scopes" section that has the variables for the `stopCallback` function.
7. Check what the value of the `tagName` variable is. Maybe we can add that to the ignore list.
8. You could also expand and poke around at the `element` variable which is the selected element when the key was pressed to see if there are any other properties that would be important to check when deciding whether or not to capture the keypress. This probably isn't necessary -- only if the `tagName` had some generic value that we don't want to ignore all the time.

**Comment by BillH99999** [comment]
Thanks for looking into it.  Will you be putting out a new version?

Thanks,
Bill

**Comment by wshanks** [comment]
Yes, it is released on github now and I submitted it to addons.thunderbird.net (which I never did for version 2.1.2).

**Comment by BillH99999** [comment]
I downloaded it from Github and the problem I reported is fixed.  I am now able to type into the search field.

Thanks!
Bill
